spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:digital-wallet}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:password}
      authentication-database: admin

server:
  port: 8080